In [185]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/raw_data_rental_listings(rent.com.bd).csv')
df.head()

,url,title,property type,property size,parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000 Sq Ft,1,1,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500 Sq Ft,2,1,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial space rent in Dhaka | 225+ Spaces f...,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,3,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250 Sq Ft,1,2,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300 Sq Ft,2,2,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [186]:
df.columns

Index(['url', 'title', 'property type', 'property size', 'parking', 'lift',
       'floor', 'price', 'service_charge', 'year built',
       'building registration type', 'preferred tennant', 'interior',
       'garage size', 'front road size', 'common area', 'bedrooms',
       'bathrooms', 'location', 'country'],
      dtype='object')

In [187]:
df.shape #shape tell us the no of rows and columns

(818, 20)

In [188]:
df.info()
#info gives us a summarty of dataset like columnname,number of null values and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   url                         818 non-null    object
 1   title                       818 non-null    object
 2   property type               818 non-null    object
 3   property size               743 non-null    object
 4   parking                     728 non-null    object
 5   lift                        727 non-null    object
 6   floor                       646 non-null    object
 7   price                       745 non-null    object
 8   service_charge              667 non-null    object
 9   year built                  743 non-null    float64
 10  building registration type  735 non-null    object
 11  preferred tennant           679 non-null    object
 12  interior                    743 non-null    object
 13  garage size                 726 non-null    object
 14  front road size             743 non-null    object
 15  common area                 743 non-null    object
 16  bedrooms                    445 non-null    object
 17  bathrooms                   444 non-null    object
 18  location                    818 non-null    object
 19  country                     818 non-null    object
dtypes: float64(1), object(19)
memory usage: 127.9+ KB

In [189]:
df.isnull() #isnull shows True where the value are missing in dataset

,url,title,property type,property size,parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False
814,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False
815,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False
816,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False
817,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False

In [190]:
df.isnull().sum() #counts the missing values in each columns

url                             0
title                           0
property type                   0
property size                  75
parking                        90
lift                           91
floor                         172
price                          73
service_charge                151
year built                     75
building registration type     83
preferred tennant             139
interior                       75
garage size                    92
front road size                75
common area                    75
bedrooms                      373
bathrooms                     374
location                        0
country                         0
dtype: int64

In [191]:
missing_percentage = (df.isnull().sum() / len(df)) * 100 #calculating the percentage of each column
missing_percentage

url                            0.000000
title                          0.000000
property type                  0.000000
property size                  9.168704
parking                       11.002445
lift                          11.124694
floor                         21.026895
price                          8.924205
service_charge                18.459658
year built                     9.168704
building registration type    10.146699
preferred tennant             16.992665
interior                       9.168704
garage size                   11.246944
front road size                9.168704
common area                    9.168704
bedrooms                      45.599022
bathrooms                     45.721271
location                       0.000000
country                        0.000000
dtype: float64

In [192]:
df.duplicated().sum()

np.int64(7)

In [193]:
df.head()

,url,title,property type,property size,parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000 Sq Ft,1,1,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500 Sq Ft,2,1,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial space rent in Dhaka | 225+ Spaces f...,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,3,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250 Sq Ft,1,2,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300 Sq Ft,2,2,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [194]:
clean_df = df.copy() #copying the data
clean_df.columns = clean_df.columns.str.strip().str.replace(" ","_") #remove space and replaceing with udnerscore(_)
clean_df.columns

Index(['url', 'title', 'property_type', 'property_size', 'parking', 'lift',
       'floor', 'price', 'service_charge', 'year_built',
       'building_registration_type', 'preferred_tennant', 'interior',
       'garage_size', 'front_road_size', 'common_area', 'bedrooms',
       'bathrooms', 'location', 'country'],
      dtype='object')

In [195]:
#dropping duplicated rows in datasets
clean_df = clean_df.drop_duplicates()
#resting indexin from zero ag
clean_df = clean_df.reset_index(drop = True)

clean_df.head()

,url,title,property_type,property_size,parking,lift,floor,price,service_charge,year_built,building_registration_type,preferred_tennant,interior,garage_size,front_road_size,common_area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000 Sq Ft,1,1,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500 Sq Ft,2,1,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial space rent in Dhaka | 225+ Spaces f...,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,3,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250 Sq Ft,1,2,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300 Sq Ft,2,2,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [196]:
# converting to lowercase
clean_df["property_type"] = clean_df["property_type"].str.lower()

#replacing propertype into categories like "residential","commerical","premium","furnished"

clean_df["property_type"] = clean_df["property_type"].replace(
    {
        "residential apartment": "residential",
        'commercial space rent in dhaka | 225+ spaces for rent with best price': 'commercial',
        'furnished apartment for rent in dhaka, residential apartment': 'furnished',
        'office space': 'commercial',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, office space': 'commercial',
        'luxury collection, residential': 'premium',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, restaurants space': 'commercial',
        'luxury collection, residential, residential apartment': 'premium',
        'furnished apartment for rent in dhaka, residential': 'furnished',
        'furnished apartment for rent in dhaka, residential, residential apartment': 'furnished',
        'furnished apartment for rent in dhaka': 'furnished',
        'restaurants space': 'commercial',
        'luxury collection, residential apartment': 'premium',
        'furnished apartment for rent in dhaka, luxury collection': 'furnished',
        'residential': 'residential',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, office space, restaurants space': 'commercial',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, office space, residential': 'residential',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, restaurants space, shop space': 'commercial',
        'furnished apartment for rent in dhaka, luxury collection, residential': 'furnished',
        'furnished apartment for rent in dhaka, luxury collection, residential, residential apartment': 'furnished',
        'residential, residential apartment': 'residential',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, office space, residential, residential apartment': 'commercial',
        'luxury collection, residential, luxury collection': 'premium',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, office space, restaurants space, shop space': 'commercial',
        'furnished apartment for rent in dhaka, luxury collection, luxury collection': 'furnished',
        'commercial space rent in dhaka | 225+ spaces for rent with best price, shop space': 'commercial'
    }
)

clean_df["property_type"] = clean_df["property_type"].str.title() #converting into title case

In [197]:
clean_df["property_type"].unique()

array(['Residential', 'Commercial', 'Furnished', 'Premium'], dtype=object)

In [198]:
clean_df['year_built'].dtype #dtype shows the data types

dtype('float64')

In [199]:
clean_df["year_built"].isna().sum() #checking nan value

np.int64(75)

In [200]:
#filling with median/avg year
# clean_df['year_built'] = clean_df['year_built'].fillna(clean_df["year_built"].median()).astype(int)

# dropping rows where there is nan value
# clean_df['year_built'] = clean_df['year_built'].astype(int)

In [201]:
clean_df["year_built"].isna().sum() #checking nan value

np.int64(75)

In [202]:
clean_df['preferred_tennant'].unique()

array([' Foreigner', 'Corporate Office or MNC Office',
       ' Corporate Office or MNC Offices', nan,
       ' Corporate Office or Restaurant', ' Restaurant',
       ' Corporate Office or Small Offices', ' Corporate or MNC Office',
       'Corporate Office or MNC Offices.',
       ' Corporate Office or MNC Offices.', ' Corporate Office',
       ' Bank Space', ' Foreigner or Local', ' Foreign Companies',
       ' Corporate Office or Small Office', ' Family',
       ' Corporate Office or MNC', ' Corporate Office, MNC',
       ' Retail Brands & Foreign Franchise', ' Restaurant Brand',
       ' Corporate Office or MNC/ Restaurant'], dtype=object)

In [203]:
#converting it into lower
clean_df['preferred_tennant'] = clean_df['preferred_tennant'].str.lower()
clean_df['preferred_tennant'] = clean_df['preferred_tennant'].replace({
     'corporate office or mnc office': 'corporate',
    'corporate office or mnc offices': 'corporate',
    'corporate office or mnc offices.': 'corporate',
    'corporate office or small offices': 'corporate',
    'corporate or mnc office': 'corporate',
    'corporate office or mnc': 'corporate',
    'corporate office, mnc': 'corporate',
    'corporate office or small office': 'corporate',
    'corporate office': 'corporate',
    'corporate office or mnc/ restaurant': 'corporate',

    # foreign
    'foreigner': 'foreign',
    'foreigner or local': 'foreign',
    'foreign companies': 'foreign',
    'retail brands & foreign franchise': 'foreign',

    # for commercial
    'restaurant': 'commercial',
    'restaurant brand': 'commercial',
    'bank space': 'commercial',
    'corporate office or restaurant': 'commercial',
    'family': 'commercial',
})

In [204]:
#  drop rows with missing tenant preference
clean_df = clean_df.dropna(subset=["preferred_tennant"])

In [205]:
clean_df["preferred_tennant"].isna().sum() #checking nan value

np.int64(0)

In [206]:
clean_df['interior'].isna().sum() #checking nan value

np.int64(0)

In [207]:
clean_df['garage_size'].isnull().sum() #checking null values

np.int64(16)

In [208]:
 #drop rows
clean_df = clean_df.dropna(subset=['garage_size']) #DROPPING EMPTY ROWS
clean_df['garage_size'].isnull().sum()

np.int64(0)

In [209]:
clean_df['front_road_size'].isnull().sum()

np.int64(0)

In [210]:
clean_df['common_area'].isnull().sum()

np.int64(0)

In [211]:
clean_df.bedrooms.unique()

array(['03 Bedrooms', '04 Bedrooms', nan, '09 Bedrooms', '05 Bedrooms',
       '01 Bedrooms', '06 Bedrooms', '02 Bedrooms',
       '03 Bedrooms+ 01 Study Room', '21 Bedrooms', '08 Bedrooms'],
      dtype=object)

In [212]:
print(clean_df["bathrooms"].value_counts(dropna=False))
print(clean_df["bathrooms"].isnull().sum())

bathrooms
NaN             282
03 Bathrooms    200
04 Bathrooms    138
05 Bathrooms     24
06 Bathrooms      4
02 Bathrooms      3
01 Bathrooms      2
09 Bathrooms      1
5 Bathrooms       1
21 Bathrooms      1
Name: count, dtype: int64
282

In [213]:
clean_df['location'].isnull().sum()

np.int64(0)

In [214]:
clean_df['country'].isnull().sum()

np.int64(0)

In [215]:
clean_df

,url,title,property_type,property_size,parking,lift,floor,price,service_charge,year_built,building_registration_type,preferred_tennant,interior,garage_size,front_road_size,common_area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential,2000 Sq Ft,1,1,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential,4500 Sq Ft,2,1,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,3,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,corporate,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential,2250 Sq Ft,1,2,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential,4300 Sq Ft,2,2,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,https://rents.com.bd/property/luxury-apartment...,Luxury Apartment For Rent In Gulshan Near Road 30,Furnished,3000 Sq Ft/ 240 Square Meter,02 Car Parking,02 available,NaN,BDT 200000,BDT 14000,2015.0,Residential,family,Furnished,300 Sq Ft,15 Ft,150 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka, Chanpara Bazar, Dhaka District...",Bangladesh
740,https://rents.com.bd/property/03-bedroom-luxur...,03 Bedroom Luxury Apartment For Rent in Gulshan,Residential,2600 Sq Ft/ 208 Square Meter,02 Car Parking,02 available,NaN,BDT 115000,BDT 10000,2019.0,Residential,family,Unfurnished,300 Sq Ft,15 Ft,150 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka, Chanpara Bazar, Dhaka District...",Bangladesh
741,https://rents.com.bd/property/fully-furnished-...,Fully Furnished Well Maintained Luxury Flat fo...,Furnished,3700 Sq Ft/ 296 Square Meter,01 Car Parking,01 available,NaN,BDT 400000,BDT 25000,2017.0,Residential,family,Furnished,150 Sq Ft,15 Ft,150 Sq Ft,04 Bedrooms,03 Bathrooms,"Gulshan, Dhaka, Chanpara Bazar, Dhaka District...",Bangladesh
742,https://rents.com.bd/property/huge-04-bedroom-...,Huge 04 Bedroom Apartment For Rent in Gulshan ...,Residential,3500 Sq Ft/ 280 Square Meter,02 Car Parking,02 available,NaN,BDT 150000,BDT 15000,2016.0,Residential,family,Unfurnished,300 Sq Ft,15 Ft,150 Sq Ft,04 Bedrooms,03 Bathrooms,"Gulshan, Dhaka, Chanpara Bazar, Dhaka District...",Bangladesh
744,https://rents.com.bd/property/stunning-furnish...,Stunning Furnished Apartment For Rent In Gulsh...,Furnished,2600 Sq Ft/ 208 Sq Meter,01 Car Parking,01 available,NaN,BDT 130000,BDT 14000,2010.0,Residential,family,Furnished,150 Sq Ft,15 Ft,150 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka, Chanpara Bazar, Dhaka District...",Bangladesh